version: "3.2"
services:
  mysql_server:
    image: mysql/mysql-server
#    image: mysql
    container_name: mysql_server
#    restart: always
    restart: on-failure
    environment: 
#      command: --default-authentication-plugin=mysql_native_password
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - db_network
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db_server
#  db_client:
  
#volumes:
#  - db-data: ../data

networks:
  db_network:
    driver: bridge
